name: math-explorations-conda
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.7.1
  - sympy=1.3
  - numpy=1.15.4
  - numpy-base=1.15.4
  - numpydoc=0.8.0=py37_0
  - networkx=2.2=py37_1
  - scipy=1.1.0
  - sympy=1.3=py37_0
  - yaml=0.1.7
  - graphviz=2.40.1
  - nbconvert=5.4.0=py37_1
  - blas=1.0=mkl
  - nbformat=4.4.0=py37_0
