name: math-explorations-conda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.1
  - sympy=1.3
  - numpy=1.15.4
  - numpy-base=1.15.4
  - numpydoc=0.8.0=py37_0
  - networkx=2.2=py37_1
  - scipy=1.1.0
  - sympy=1.3=py37_0
  - yaml=0.1.7
  - graphviz=2.40.1
  - nbconvert=5.4.0=py37_1
  - blas=1.0=mkl
  - nbformat=4.4.0=py37_0
  - conda=4.6.8=py37_0
  - conda-build=3.17.6=py37_0
  - conda-env=2.6.0=1
  - conda-verify=3.1.1=py37_0
  - plotly=3.7.0
  - notebook=5.7.4=py37_0
  - ipykernel=5.1.0
  - ipython=7.2.0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.4.2=py37_0