name: math-explorations-conda
channels:
  - conda-forge
  - defaults
dependencies:
  - sympy
  - numpy
  - numpy-base
  - networkx
  - scipy
  - sympy
  - graphviz
  - matplotlib
  - nbconvert
  - nbformat
  - plotly
  - notebook
  - ipywidgets
  - ffmpeg
  - ca-certificates
  - certifi
  - freetype
  - jpeg
  - libcxx
  - libedit
  - libffi
  - libpng
  - libtiff
  - ncurses
  - olefile
  - openssl
  - pillow
  - pip
  - python
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - zstd